# Generated by Django 3.0.8 on 2020-07-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
