# Generated by Django 3.0.8 on 2020-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0002_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Indonesia', max_length=50, verbose_name='language'),
            preserve_default=False,
        ),
    ]
