# Generated by Django 3.0.8 on 2020-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0003_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('sub_title', models.CharField(max_length=50, verbose_name='sub_title')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
