# Generated by Django 3.0.8 on 2020-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='readingmaterial.Book'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='stories',
            field=models.ManyToManyField(blank=True, null=True, to='readingmaterial.Story'),
        ),
    ]
